<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_with_Google</name>
   <tag></tag>
   <elementGuidId>5ea7a170-f477-442e-bbf6-fcfd7727cc3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.social-button.large.google-plus.circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-form-popup']/div/div/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c79ecb5-c458-4c5d-a027-4cffb1ac8438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.psegameshop.com/wp-login.php?loginSocial=google</value>
      <webElementGuid>c881ed15-7be7-4543-88aa-788418f5d0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button social-button large google-plus circle</value>
      <webElementGuid>f95fb828-a6fe-4680-a7a1-b578887f4e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plugin</name>
      <type>Main</type>
      <value>nsl</value>
      <webElementGuid>1155ffea-295a-45df-8134-b39ba7a89288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>connect</value>
      <webElementGuid>425a023e-c621-45a5-afb5-8ae481d8706a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-redirect</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>b5b69296-8c23-4c84-aeb3-9b17579a08f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provider</name>
      <type>Main</type>
      <value>google</value>
      <webElementGuid>02fd855c-ae33-4fca-ae4f-e27d0f5791ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popupwidth</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>23dc8d12-da04-440d-9542-451e53ed4dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popupheight</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>80012174-a033-4afa-8668-ed61462457aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							
							Login with Google
						</value>
      <webElementGuid>0182ae12-d614-4ed9-90b3-8d57cfca8f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-popup&quot;)/div[@class=&quot;my-account-header page-title normal-title&quot;]/div[@class=&quot;page-title-inner flex-row container
	 text-left&quot;]/div[@class=&quot;flex-col flex-grow medium-text-center&quot;]/div[@class=&quot;text-center social-login&quot;]/a[@class=&quot;button social-button large google-plus circle&quot;]</value>
      <webElementGuid>c4b22ae3-f4e0-4d98-b9c3-d21c268aad55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form-popup']/div/div/div/div/a[2]</value>
      <webElementGuid>882cf321-1d06-4a58-8f24-ddd08036f99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::a[1]</value>
      <webElementGuid>a9dad561-dd12-428b-a8c5-8bf34bdd0d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.psegameshop.com/wp-login.php?loginSocial=google')]</value>
      <webElementGuid>b914fc87-1b4b-4b66-b968-3d2de1e29c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>bda92394-96ee-4ff8-9938-89dab8473126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.psegameshop.com/wp-login.php?loginSocial=google' and (text() = '
							
							Login with Google
						' or . = '
							
							Login with Google
						')]</value>
      <webElementGuid>afad5669-e5b2-4135-8ae3-db53ca457d6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
