<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login_with_Facebook</name>
   <tag></tag>
   <elementGuidId>fc31954e-4842-40ee-9346-47174ac9527d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.button.social-button.large.facebook.circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-form-popup']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33b762ba-f543-4a5d-a889-1c7b5cc13d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.psegameshop.com/wp-login.php?loginSocial=facebook</value>
      <webElementGuid>df8cbf21-bece-496a-ab71-ea0c9dbd4989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button social-button large facebook circle</value>
      <webElementGuid>6a1b88ec-3e7e-4ee9-b775-bc6546122df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-plugin</name>
      <type>Main</type>
      <value>nsl</value>
      <webElementGuid>7c7465d7-bc60-46a8-adee-d0a11b22178d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>connect</value>
      <webElementGuid>c2d78d79-bae0-49c6-ac96-4b843ef72952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-redirect</name>
      <type>Main</type>
      <value>current</value>
      <webElementGuid>fa636e59-5ff3-40e8-9afc-226b188f1735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-provider</name>
      <type>Main</type>
      <value>facebook</value>
      <webElementGuid>ab453d16-653b-4dc3-afaf-afe923de4c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popupwidth</name>
      <type>Main</type>
      <value>475</value>
      <webElementGuid>33cf8c6d-82cb-46ac-bdf1-55e309afd23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-popupheight</name>
      <type>Main</type>
      <value>175</value>
      <webElementGuid>e72e8aa7-29a9-466d-9b6d-20cad87473bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							
							Login with Facebook
						</value>
      <webElementGuid>e935669b-e0f6-4c17-8749-35b43a262727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form-popup&quot;)/div[@class=&quot;my-account-header page-title normal-title&quot;]/div[@class=&quot;page-title-inner flex-row container
	 text-left&quot;]/div[@class=&quot;flex-col flex-grow medium-text-center&quot;]/div[@class=&quot;text-center social-login&quot;]/a[@class=&quot;button social-button large facebook circle&quot;]</value>
      <webElementGuid>ee7d6969-e71f-4f1e-b74a-32392fb2e0cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-form-popup']/div/div/div/div/a</value>
      <webElementGuid>f8c2530f-acc9-42f7-b8d1-faf00370bf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.psegameshop.com/wp-login.php?loginSocial=facebook')]</value>
      <webElementGuid>660eb58d-7bb9-4cc5-949b-9e5ac05611a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>dc71b99e-ad53-4080-9868-973813779edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.psegameshop.com/wp-login.php?loginSocial=facebook' and (text() = '
							
							Login with Facebook
						' or . = '
							
							Login with Facebook
						')]</value>
      <webElementGuid>4578905d-8402-4bf6-9c9d-554abae56c25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
