<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pesan_register</name>
   <tag></tag>
   <elementGuidId>6e4cfc1e-29b8-4aa2-9aa6-dedd41c44a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>css=div.message-container.container.success-color.medium-text-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
