<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_username</name>
   <tag></tag>
   <elementGuidId>850c7828-031c-40b6-8977-b010785d50d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div[2]/div/div/div[2]/div/div/p/strong</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'mastomcsc23' or . = 'mastomcsc23')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.woocommerce-MyAccount-content > p > strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>92314060-278b-4e5a-be3f-1a974f532017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mastomcsc23</value>
      <webElementGuid>aa0414de-5ac0-4ec3-a169-93a1d8b0f16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;page-wrapper my-account mb&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row vertical-tabs&quot;]/div[@class=&quot;large-9 col&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-MyAccount-content&quot;]/p[1]/strong[1]</value>
      <webElementGuid>41d4eb55-5496-4e30-9cdc-c651a1021fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/div[2]/div/div/p/strong</value>
      <webElementGuid>ac25d36b-8333-4c87-9cf0-572fb476b263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::strong[1]</value>
      <webElementGuid>19b61bce-65a7-4763-8d1e-067237a0d5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[2]/following::strong[1]</value>
      <webElementGuid>28cb6f80-4c2a-4efe-ba8e-6f5d483ef21e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mastomcsc23'])[2]/preceding::strong[1]</value>
      <webElementGuid>43ae40c3-a0ec-4f8e-ac6e-5e17897ba174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::strong[2]</value>
      <webElementGuid>d2f08f34-5ed3-4279-a8c2-3afb8b8dfb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p/strong</value>
      <webElementGuid>a9a0167b-1fd4-4f10-88cc-05245eb88bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'mastomcsc23' or . = 'mastomcsc23')]</value>
      <webElementGuid>3edc9e56-96a2-4447-ae1a-2c5b1542aef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
